# Reading text files

Modes
- read "r"
- write "w"
- append "a"
- read+write "r+"

### read()

In [6]:
data=open(r"C:\Users\dearh\Downloads\MIDC BATCH 02 AI-BIA\file operations\open.text","r")

In [7]:
#using read()
data.read()

'Radhe Radhe\nJai Jagannath'

In [8]:
data.close()

In [9]:
#using for loop
data=open(r"C:\Users\dearh\Downloads\MIDC BATCH 02 AI-BIA\file operations\open.text","r")
for content in data:
    print(content)

Radhe Radhe

Jai Jagannath

In [10]:
data.close()

### write()

#### Writing data into existing file

In [11]:
data=open(r"C:\Users\dearh\Downloads\MIDC BATCH 02 AI-BIA\file operations\open2.text","w")
data.write("writing in text file")

20

In [12]:
data.write(" \n hello")

8

In [13]:
data.close()

#### writing data into new file

In [20]:
data=open(r"C:\Users\dearh\Downloads\MIDC BATCH 02 AI-BIA\file operations\open2.text","w")
data.write("i am AI Engineer \ni am learning write mode")

42

In [21]:
data.close()

### append()

In [22]:
data=open(r"C:\Users\dearh\Downloads\MIDC BATCH 02 AI-BIA\file operations\open2.text","a")
data.write("\ni am from nagpur")
data.close()

In [23]:
data=open(r"C:\Users\dearh\Downloads\MIDC BATCH 02 AI-BIA\file operations\open2.text","r")

In [24]:
for i in data:
    print(i)

i am AI Engineer

i am learning write mode

i am from nagpur

In [25]:
data.close()

### r+ mode

In [26]:
data=open(r"C:\Users\dearh\Downloads\MIDC BATCH 02 AI-BIA\file operations\open2.text","r+")
print(data.write("i am learning python"))
for i in data:
    print(i)

20
 am learning write mode

i am from nagpur

In [27]:
data.close()

## with open

In [28]:
with open(r"C:\Users\dearh\Downloads\MIDC BATCH 02 AI-BIA\file operations\open2.text","r") as file:
    data=file.read()
    print(data)

i am learning python am learning write mode
i am from nagpur

In [30]:
with open(r"C:\Users\dearh\Downloads\MIDC BATCH 02 AI-BIA\file operations\open2.text","w") as file:
    data=file.write("i am data analyst")
    print(data)

17

In [31]:
with open(r"C:\Users\dearh\Downloads\MIDC BATCH 02 AI-BIA\file operations\open2.text","r+") as file:
    print(file.read())
    print(file.write("i am data scientist"))
    print(file.read())

i am data analyst
19

# reading excel and csv file

excel: rows and columns
csv: comma seperated file
tsv: tab seperated file

In [32]:
import pandas as pd

In [33]:
print(dir(pd))

['ArrowDtype', 'BooleanDtype', 'Categorical', 'CategoricalDtype', 'CategoricalIndex', 'DataFrame', 'DateOffset', 'DatetimeIndex', 'DatetimeTZDtype', 'ExcelFile', 'ExcelWriter', 'Flags', 'Float32Dtype', 'Float64Dtype', 'Grouper', 'HDFStore', 'Index', 'IndexSlice', 'Int16Dtype', 'Int32Dtype', 'Int64Dtype', 'Int8Dtype', 'Interval', 'IntervalDtype', 'IntervalIndex', 'MultiIndex', 'NA', 'NaT', 'NamedAgg', 'Period', 'PeriodDtype', 'PeriodIndex', 'RangeIndex', 'Series', 'SparseDtype', 'StringDtype', 'Timedelta', 'TimedeltaIndex', 'Timestamp', 'UInt16Dtype', 'UInt32Dtype', 'UInt64Dtype', 'UInt8Dtype', '__all__', '__builtins__', '__cached__', '__doc__', '__docformat__', '__file__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_built_with_meson', '_config', '_is_numpy_dev', '_libs', '_pandas_datetime_CAPI', '_pandas_parser_CAPI', '_testing', '_typing', '_version_meson', 'annotations', 'api', 'array', 'arrays', 'bdate_range', 'compat', 'concat', 'core', 'crosstab', 'cut', 'date_range', 'describe_option', 'errors', 'eval', 'factorize', 'from_dummies', 'get_dummies', 'get_option', 'infer_freq', 'interval_range', 'io', 'isna', 'isnull', 'json_normalize', 'lreshape', 'melt', 'merge', 'merge_asof', 'merge_ordered', 'notna', 'notnull', 'offsets', 'option_context', 'options', 'pandas', 'period_range', 'pivot', 'pivot_table', 'plotting', 'qcut', 'read_clipboard', 'read_csv', 'read_excel', 'read_feather', 'read_fwf', 'read_gbq', 'read_hdf', 'read_html', 'read_json', 'read_orc', 'read_parquet', 'read_pickle', 'read_sas', 'read_spss', 'read_sql', 'read_sql_query', 'read_sql_table', 'read_stata', 'read_table', 'read_xml', 'reset_option', 'set_eng_float_format', 'set_option', 'show_versions', 'test', 'testing', 'timedelta_range', 'to_datetime', 'to_numeric', 'to_pickle', 'to_timedelta', 'tseries', 'unique', 'util', 'value_counts', 'wide_to_long']

- read_csv()
- read_excel()

In [67]:
data=pd.read_csv(r"C:\Users\dearh\Downloads\MIDC BATCH 02 AI-BIA\file operations\Bigmart_data.csv")

In [35]:
data

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,FDW58,20.750,Low Fat,0.007565,Snack Foods,107.8622,OUT049,1999,Medium,Tier 1,Supermarket Type1
1,FDW14,8.300,reg,0.038428,Dairy,87.3198,OUT017,2007,NaN,Tier 2,Supermarket Type1
2,NCN55,14.600,Low Fat,0.099575,Others,241.7538,OUT010,1998,NaN,Tier 3,Grocery Store
3,FDQ58,7.315,Low Fat,0.015388,Snack Foods,155.0340,OUT017,2007,NaN,Tier 2,Supermarket Type1
4,FDY38,NaN,Regular,0.118599,Dairy,234.2300,OUT027,1985,Medium,Tier 3,Supermarket Type3
...,...,...,...,...,...,...,...,...,...,...,...
5676,FDB58,10.500,Regular,0.013496,Snack Foods,141.3154,OUT046,1997,Small,Tier 1,Supermarket Type1
5677,FDD47,7.600,Regular,0.142991,Starchy Foods,169.1448,OUT018,2009,Medium,Tier 3,Supermarket Type2
5678,NCO17,10.000,Low Fat,0.073529,Health and Hygiene,118.7440,OUT045,2002,NaN,Tier 2,Supermarket Type1
5679,FDJ26,15.300,Regular,0.000000,Canned,214.6218,OUT017,2007,NaN,Tier 2,Supermarket Type1
5680,FDU37,9.500,Regular,0.104720,Canned,79.7960,OUT045,2002,NaN,Tier 2,Supermarket Type1

In [36]:
#pip install xlrd
#install this xlrd module when ur file extemsion is .xls

In [69]:
data=pd.read_excel(r"C:\Users\dearh\Downloads\MIDC BATCH 02 AI-BIA\file operations\whether_data.xls") #xlsx

In [70]:
data

          day  temperature  windspeed   event
0  2017-01-01         32.0        6.0    Rain
1  2017-01-04          NaN        7.0   Sunny
2  2017-01-05         28.0        NaN    Snow
3  2017-01-06          NaN        7.0     NaN
4  2017-01-07         32.0        NaN    Rain
5  2017-01-08         31.0        2.0   Sunny
6  2017-01-09          NaN        NaN     NaN
7  2017-01-10         34.0        8.0  Cloudy
8  2017-01-11         40.0       12.0     NaN
9  2017-01-10         34.0        8.0  Cloudy
10 2017-01-11         40.0       12.0     NaN

In [41]:
data1=pd.read_excel(r"C:\Users\dearh\Downloads\MIDC BATCH 02 AI-BIA\file operations\whether_data.xlsx") #xlsx

In [42]:
data1

          day  temperature  windspeed   event
0  2017-01-01         32.0        6.0    Rain
1  2017-01-04          NaN        7.0   Sunny
2  2017-01-05         28.0        NaN    Snow
3  2017-01-06          NaN        7.0     NaN
4  2017-01-07         32.0        NaN    Rain
5  2017-01-08         31.0        2.0   Sunny
6  2017-01-09          NaN        NaN     NaN
7  2017-01-10         34.0        8.0  Cloudy
8  2017-01-11         40.0       12.0     NaN
9  2017-01-10         34.0        8.0  Cloudy
10 2017-01-11         40.0       12.0     NaN

#### HTML or XML files reading

In [43]:
data=open(r"C:\Users\dearh\Downloads\MIDC BATCH 02 AI-BIA\file operations\books.xml")

In [44]:
data1=data.read()
data1

"<library>\n <book>\n <title>Harry Potter and the Sorcerer's Stone</title>\n <author>J.K. Rowling</author>\n <year>1997</year>\n </book>\n <book>\n <title>The Great Gatsby</title>\n <author>F. Scott Fitzgerald</author>\n <year>1925</year>\n </book>\n <book>\n <title>To Kill a Mockingbird</title>\n <author>Harper Lee</author>\n <year>1960</year>\n </book>\n</library>"

#### bs4 library Beautifulsoup module

The BeautifulSoup module is part of the beautifulsoup4 library in Python, which is commonly used for web scraping and parsing HTML or XML documents.

In [46]:
import sys, subprocess

try:
    from bs4 import BeautifulSoup as bs
except ModuleNotFoundError:
    subprocess.check_call([sys.executable, "-m", "pip", "install", "beautifulsoup4"])
    from bs4 import BeautifulSoup as bs

In [47]:
clean_data=bs(data1,"xml")

In [48]:
print(clean_data)

<?xml version="1.0" encoding="utf-8"?>
<library>
<book>
<title>Harry Potter and the Sorcerer's Stone</title>
<author>J.K. Rowling</author>
<year>1997</year>
</book>
<book>
<title>The Great Gatsby</title>
<author>F. Scott Fitzgerald</author>
<year>1925</year>
</book>
<book>
<title>To Kill a Mockingbird</title>
<author>Harper Lee</author>
<year>1960</year>
</book>
</library>

In [49]:
#to find multiple tags we use find_all() 
title_tgs=clean_data.find_all("title")
title_tgs

[<title>Harry Potter and the Sorcerer's Stone</title>,
 <title>The Great Gatsby</title>,
 <title>To Kill a Mockingbird</title>]

In [50]:
for i in title_tgs:
    print(i.get_text())

Harry Potter and the Sorcerer's Stone
The Great Gatsby
To Kill a Mockingbird

In [51]:
#to find single or first tag we use find() 
data2=clean_data.find("title")
data2

In [52]:
data2.get_text()

"Harry Potter and the Sorcerer's Stone"

In [53]:
year=clean_data.find("year")

In [54]:
year

In [55]:
year.get_text()

'1997'

In [56]:
year=clean_data.find_all("year")
year

In [57]:
for y in year:
    print(y.get_text())

1997
1925
1960

# To read json

In [58]:
import json

In [59]:
json_file=open(r"C:\Users\dearh\Downloads\MIDC BATCH 02 AI-BIA\file operations\data.json")

In [60]:
data=json.load(json_file)

In [61]:
data

{'emp_details': [{'emp_name': 'Sayli',
   'email': 'sayali123@gmail.com',
   'job_prtofile': 'data scintist'},
  {'emp_name': 'prachi',
   'email': 'prachi123@gmail.com',
   'job_prtofile': 'dataanalyst'},
  {'emp_name': 'Gauri',
   'email': 'Gauri123@gmail.com',
   'job_prtofile': 'It Engineer'}],
 'emp_salary': [{'emp_name': 'Sayli', 'salary': 20000},
  {'emp_name': 'prachi', 'salary': 30000},
  {'emp_name': 'Gauri', 'salary': 50000}]}

In [62]:
for i in data['emp_details']:
    print(i)

{'emp_name': 'Sayli', 'email': 'sayali123@gmail.com', 'job_prtofile': 'data scintist'}
{'emp_name': 'prachi', 'email': 'prachi123@gmail.com', 'job_prtofile': 'dataanalyst'}
{'emp_name': 'Gauri', 'email': 'Gauri123@gmail.com', 'job_prtofile': 'It Engineer'}

In [63]:
for i in data['emp_salary']:
    print(i)

{'emp_name': 'Sayli', 'salary': 20000}
{'emp_name': 'prachi', 'salary': 30000}
{'emp_name': 'Gauri', 'salary': 50000}

In [64]:
for i in data['emp_details','emp_salary']:
    print(i)

KeyError: ('emp_details', 'emp_salary')